### ISSUE TITLE
Possible Support for Arm64 or Arm?

### ISSUE THREAD

**Issue by Jiacheng-WU** [Sedeniono/tiny-optional#2]
So fantastic!! I really love this library!
But I am curious why you didn't support the arm architecture. 
Is it similar to x86 (arm) and x64 (aarch64) or is there anything I do not consider?

**Comment by Sedeniono** [comment]
The library currently does not support ARM because I am not really familiar enough with the ARM platform to be confident that the way I am exploiting undefined behavior works also on ARM. For example, for `double` I am using a specific qNaN bit pattern because I am pretty confident that nothing in today's x86 or x64 ecosystem (AMD/Intel CPUs, usual compilers, usual operating systems) exploits the freedom in the NaNs allowed by the IEEE754 standard. But I have no idea whether that is also true for ARM in general, or never, or only for specific ARM based systems. After all, the ARM world is much more diverse, so attempting to exploit undefined behavior without actually causing problems becomes much more difficult. Similar for the other tricks that I am using (bools and pointers, at the moment).

One thing that would of course be possible is to remove the parts that rely on undefined behavior when not compiling for x86/x64. This boils down to not using `SentinelForExploitingUnusedBits`, `MemcpyAndCmpFlagManipulator` and maybe `InplaceDecompositionViaMemPtr` in the implementation. All of the remaining code is conforming to the C++ standard. However, that would mean that e.g. `tiny::optional<double>` uses an additional bool again. So there would be no advantage over `std::optional<double>`, defeating one of the goals of the library. But the second feature, allowing to specify a sentinel (e.g. `tiny::optional<int, -1>`) and thereby not requiring the additional bool would still work. Not really sure if this alone would warrant the work.

Currently, I am not planning on supporting ARM one way or the other. But of course, the library is open source, so anyone with the necessary knowledge is welcome to do so 😉

**Comment by Jiacheng-WU** [comment]
Got it, Thanks a lot!
