### ISSUE TITLE
Request: Natvis visualizer for Visual Studio

### ISSUE THREAD

**Issue by moggabor** [Sedeniono/tiny-optional#5]
It would be useful to add a Natvis visualizer (https://learn.microsoft.com/en-us/visualstudio/debugger/create-custom-views-of-native-objects) for tiny::optional.

For example here is how tiny::optional currently looks in Visual Studio as compared to std::optional:
![image](https://github.com/Sedeniono/tiny-optional/assets/7282014/91babfcd-4a2e-47fe-b1f1-40037d361a31)

**Comment by Sedeniono** [comment]
@moggabor thanks for the suggestion! I added some natvis visualizers in commit 87720591bdd1e907100c3d42dc2409014f82729e. Also see the caveats in the updated readme. But if not using the fancy "store empty state in a member" feature or custom specializations of `tiny::optional_flag_manipulator`, the visualizers should just work as expected. Please have a go and see if it works for you sufficiently.

**Comment by Sedeniono** [comment]
I managed to find a way to get the visualizers working also with the "store empty state in member" feature (e0052e417b87af9f1c13107f2e389c3ee3101aa2). So, the current Natvis file in the [`include` directory](https://github.com/Sedeniono/tiny-optional/tree/main/include) now properly works with all built-in sentinels and special bit patterns (and of course if still an extra internal boolean is used).

Unfortunately, if a custom specialized `tiny::optional_flag_manipulator` is used, I couldn't find a way to implement a generic Natvis visualizer. The underlying issue is that Natvis does not allow to execute any functions, so it cannot call the specialized `tiny::optional_flag_manipulator` in any way. The Natvis visualizer will then simply tell you "preview not support" and shows the raw storage.

I released a new version [v1.2.0](https://github.com/Sedeniono/tiny-optional/releases/tag/v1.2.0) where all changes are included.

**Comment by moggabor** [comment]
@Sedeniono thank you for implementing my suggestion!

I tried it and first it didn't work. The watch window showed completely empty lines for optionals. After setting "Natvis diagnostic messages" to Verbose, I found the following error:
```
tiny_optional.natvis(51,59): Error: identifier "std::nullopt" is undefined
    Error while evaluating 'std::nullopt' in the context of type 'example.dll!tiny::impl::TinyOptionalImpl<tiny::impl::InplaceStoredTypeDecomposition<float>,tiny::optional_flag_manipulator<float,void>>'.
```
After removing line 51 it started working. I didn't look further into what was the problem.
![image](https://github.com/Sedeniono/tiny-optional/assets/7282014/c2786b2f-be5c-4f7c-a481-d19d5aaeaf0f)

For reference I'm using `optional_aip<float>`, `optional_aip<int>`, `optional_aip<bool>` and I'm not using custom `tiny::optional_flag_manipulator`.

Anyway I can live without this line, it's not a big deal.

**Comment by Sedeniono** [comment]
@moggabor After playing around with it, I think this happens if no translation unit uses `std::nullopt`. In this case, the symbol `std::nullopt` probably does not appear in the debug information and therefore natvis fails to resolve it. Or something like this. Just a guess. In any case, I now replaced `std::nullopt` with a simple string to work around the issue in 8aeb671f9b6abcece17cf071c6870de1d74f9e37.

Of course, commenting out the natvis line also works. If the optional is empty, it simply shows no `value` field in the debugger.
