### ISSUE TITLE
What's a good way to deal with std::chrono::duration

### ISSUE THREAD

**Issue by mjoras** [Sedeniono/tiny-optional#6]
We have a lot of optionals of the form `optional<std::chrono::microseconds>`. This in principle seems like a great candidate for the integral-based optionality, e.g. by storing `std::chrono::microseconds::min()` as the sentinel. However, I can't seem to get that to work with any of the existing types. Is there something I am missing or are there some complexities here preventing a duration from being stored inplace?

**Comment by mjoras** [comment]
Maybe I just need a flag manipulator like this?

```
struct MicrosecondsFlagManipulator {
  static bool is_empty(const std::chrono::microseconds& t) noexcept
    {
        return t == std::chrono::microseconds::min();
    }

    static void init_empty_flag(std::chrono::microseconds& t) noexcept
    {
        ::new (&t) std::chrono::microseconds(std::chrono::microseconds::min());
    }

    static void invalidate_empty_flag(std::chrono::microseconds& t) noexcept
    {
        std::destroy(t);
    }

};
```

**Comment by Sedeniono** [comment]
The obvious thing
```C++
tiny::optional<std::chrono::microseconds, std::chrono::microseconds::min()> o;
```
does not work because `std::chrono::duration` is not a literal class type (and only those are supported as non-type template parameters by C++).

However, you can use `tiny::optional_sentinel_via_type`:
```C++
struct MicroSecondsSentinel
{
  static constexpr auto value = std::chrono::microseconds::min();
};

tiny::optional_sentinel_via_type<std::chrono::microseconds, MicroSecondsSentinel> o;
```
(and maybe abbreviate that with an appropriate alias). This works because `std::chrono::microseconds::min()` is `constexpr`.

Writing a custom `MicrosecondsFlagManipulator` as you did would work in principle. However, it is brittle, because you cannot place the `MicrosecondsFlagManipulator` right below the definition of `std::chrono::microseconds` because you cannot modify the `<chrono>` header. I explained the problems with this approach [in the readme](https://github.com/Sedeniono/tiny-optional?tab=readme-ov-file#types-that-you-have-not-authored).

**Comment by mjoras** [comment]
Thanks!
